### ISSUE TITLE
问题：运行成功，但未成功签到

### ISSUE THREAD

**Issue by zhenghan123** [Jejz168/V2free#1]
![image](https://github.com/Jejz168/V2free/assets/61129862/4e5b91c3-6a11-4981-a132-addebd2a0b01)
![image](https://github.com/Jejz168/V2free/assets/61129862/916aa097-2529-4310-8edb-649fd57ae272)

**Comment by Jejz168** [comment]
有机器人验证了，废了

**Comment by zhenghan123** [comment]
好吧。
